export const activities = [
    {
      id: 1,
      activity: "Create a Story Presentation",
      examples: [
        "Indian History",
        "Journey to Mars",
        "Dive into the Ocean",
        "World War 3",
        "First Person on Earth",
        "Dooms Day",
        "Evolution of AI",
        "Evolution of New Religion",
        "Cat on an Island",
        "A Person That Cannot Change His Mind",
      ],
      tools: ["Presentation Generator"],
    },
    {
      id: 2,
      activity: "Create a Comic Book",
      examples: [
        "The Battle Between Spiderman and Chota Bheem",
        "Iron Man and Astro Boy: Mechanical Hearts",
        "Superman vs. Doraemon: Battle for the 5th Dimension",
        "Quantum Entangled: Fates in Parallel",
        "The Flash Races Sonic the Hedgehog",
        "Teenage Mutant Ninja Turtles vs. The Super Saiyans",
        "Deadpool's Adventures with Tom and Jerry",
        "The Avengers Meet Pokémon: Infinity Poké Ball",
        "Captain America in the World of Dragon Ball",
        "Groot and Totoro: Forest Guardians",
      ],
      tools: ["Comic Strip Generator"],
    },
    {
      id: 3,
      activity: "Create a Picture Album",
      examples: [
        "My Magical Pet Adventures",
        "Space Explorers: Journey to Planet X",
        "Underwater Kingdom Champions",
        "Backyard Safari Discoveries",
        "Time-Traveling History Detectives",
        "Foods vs. Monsters Battle Royale",
        "Cloud Kingdom Chronicles",
        "Miniature Heroes: The Tiny Defenders",
        "My Robot Buddy",
        "Enchanted Classroom",
      ],
      tools: ["Image Generator"],
    },
    {
      id: 4,
      activity: "Create a Video",
      examples: [
        "Our Community Heroes",
        "Mini Science Explainers",
        "Earth Guardians",
        "Math in Real Life",
        "Literary Character Interviews",
        "Time Capsule 2025",
        "World Culture Spotlights",
        "Future Inventions",
        "Historical Moment Re-tellings",
        "Animal Habitat Tours",
      ],
      tools: ["Video Generator", "Text to Speech", "Video Editor"],
    },
    {
      id: 5,
      activity: "Create a Personalized Study Plan for an Upcoming Exam",
      examples: [
        "A study plan with 2 hours a day for 10 days targeting a board exam",
        "A study plan with 1 hour a day for 4 days targeting a math olympiad",
      ],
      tools: ["Study Plan Generator"],
    },
    {
      id: 6,
      activity: "Generate and Take an Assessment Test and Get Feedback",
      examples: [
        "Generate a Math Assessment",
        "Generate a Science Assessment",
        "Generate a Biology Assessment",
        "Generate a Social Assessment",
        "Generate an English Assessment",
      ],
      tools: ["Assessment Generator"],
    },
    {
      id: 7,
      activity: "Create a Subject Presentation",
      examples: [
        "Create a Presentation on Sound",
        "Create a Presentation on Photosynthesis",
        "Create a Presentation on Space",
        "Create a Presentation on Types of Metals",
        "Create a Presentation on Thermodynamics",
      ],
      tools: ["Presentation Generator"],
    },
    {
      id: 8,
      activity: "Learn a Lesson from Agent Buddy",
      examples: [
        "Learn About Fractions and mixed numbers",
        "Learn About Ratios and rates",
        "Learn About Crop Production and Management",
        "Learn About Carbon and Its Compounds",
        "Learn About Light Reflection and Refraction",
        "Learn About Magnetic Effects and Electric Current",
        "Learn About Acids, Bases and Salts",
        "Learn About Weather and the Atmosphere",
        "Learn About Exponents and Order of Operations",
        "Learn About Negative Numbers",
      ],
      tools: ["AI Tutor"],
    },
    {
      id: 9,
      activity: "Play with PDF Documents",
      examples: [
        "Summarise the Given Document",
        "Ask Questions from Multiple Documents",
        "Create a Timeline of Activities from the Given Documents",
        "Compare Two Documents",
        "Generate an Article from PDF Documents",
        "Create an Assessment Test Out of Selected PDF Doducments",
      ],
      tools: ["Chat with Docs"],
    },
    {
      id: 10,
      activity: "Chat with Youtube Videos",
      examples: [
        "Create Summaries of Videos",
        "Create an Assessment Out of Video",
      ],
      tools: ["YouTube Summary"],
    },
    {
      id: 11,
      activity: "Create a Research Document",
      examples: [
        "Assessing microplastic pollution in local water bodies",
        "Studying urban heat islands in rapidly developing cities",
        "Documenting local biodiversity and creating community conservation plans",
        "Evaluating drought-resistant crop varieties suitable for local conditions",
        "Developing low-cost food preservation methods for rural communities",
        "Surveying medicinal plants used in traditional remedies and assessing their properties",
        "Designing and testing low-cost water filtration systems",
        "Mapping access to educational resources across different communities",
        "Examining factors affecting girls' participation in STEM education",
        "Investigating antimicrobial properties of common household spices",
      ],
      tools: ["Research Assistant"],
    },
    {
      id: 12,
      activity: "Update and Publish Portfolio",
      examples: [],
      tools: ["Document Generator"],
    },
    {
      id: 13,
      activity: "Create a Video Script and Screen Play",
      examples: [
        "The Hidden Life of Urban Wildlife: Exploring Ecosystems in Your City",
        "Sustainable Fashion Revolution: From Fast Fashion to Ethical Choices",
        "Forgotten Scientists Who Changed the World: Unsung Heroes of Discovery",
        "Traditional Medicine Meets Modern Science: Ancient Wisdom in Today's Labs",
        "The Mathematics of Music: How Patterns Create Harmony",
        "Plastic Planet: Innovative Solutions to Our Global Waste Crisis",
        "The Psychology of Social Media: How Platforms Engineer Our Attention",
        "Water Crisis 2030: Conservation Technologies That Could Save Us",
        "The Secret Language of Birds: Decoding Nature's Symphony",
        "Space Junk: The Unseen Pollution Orbiting Our Planet",
      ],
      tools: ["School Promotional Video Script"],
    },
    {
      id: 14,
      activity: "Build Creatives with Code",
      examples: [
        "Build Sine and Cosine Animation",
        "Build Orbit Control",
        "Build Smoke Particles",
        "Build Clock",
        "Build Triangle Strip",
        "Build Geometries",
      ],
      tools: ["Creative Coding Playground"],
    },
    {
      id: 15,
      activity: "Debate with Agent Buddy",
      examples: [
        "Social Media Regulation: Necessary Protection or Infringement on Free Speech?",
        "Standardized Testing Should Be Abolished in Modern Education Systems",
        "Mandatory Climate Change Education: Essential Knowledge for Future Generations",
        "Space Exploration: An Unjustifiable Luxury in the Face of Global Poverty",
        "Artificial Intelligence in Classrooms Undermines Authentic Learning and Critical Thinking",
        "Universal Basic Income: Economic Safety Net or Pathway to Societal Complacency?",
        "Government Surveillance Powers: Security Necessity or Privacy Violation?",
        "The Voting Age Should Be Lowered to 16 in Democratic Nations",
        "Cultural Preservation Must Take Priority Over Globalization's Economic Benefits",
        "Genetic Engineering of Humans: Ethical Advancement or Dangerous Interference?",
      ],
      tools: ["AI Tutor"],
    },
    {
      id: 16,
      activity: "Create an AI App",
      examples: [
        "Recipe Maker",
        "Travel Planner",
        "Story Maker",
        "Book Suggestion Maker",
      ],
      tools: ["App Builder"],
    },
    {
      id: 17,
      activity: "Experience Image Recognition Model on Teachable Machine",
      examples: [
        "Cats and Dogs",
        "Big Dogs and Small Dogs",
        "Cars and Bikes",
        "Humans and Monkeys",
        "Computer and Laptops",
        "Mangoes and Oranges",
        "Bicycles and Scooters",
        "Water Bottles and Cups",
        "Male and Female Faces",
        "Children and Adults",
      ],
      tools: ["Teachable Machine"],
    },
    {
      id: 18,
      activity: "Create a Song",
      examples: [
        "Digital Daydream",
        "Heroes of Our Own Story",
        "The Middle School Mystery",
        "Unstoppable Tomorrow",
        "Friends Through the Chaos",
        "Screen Time Serenade",
        "Growing Pains and Shooting Stars",
        "The Lunchroom Chronicles",
        "Finding My Voice",
        "This Moment is Everything",
      ],
      tools: ["Song Generator"],
    },
    {
      id: 19,
      activity: "Create Voice Over",
      examples: [
        "The Secret Passage in the School Library",
        "Switching Lives with My Best Friend for a Day",
        "The Last Summer Before High School",
        "Messages from Another Dimension",
        "The Neighborhood Time Capsule",
        "When the Internet Disappeared",
        "The Science Fair Disaster That Saved the Day",
        "Finding Courage on the School Bus",
        "The Family Recipe That Changed Everything",
        "The Club of Misfits Who Became Heroes",
      ],
      tools: ["Story Generator", "Text to Speech"],
    },
    {
      id: 20,
      activity: "Plan for an AI Product Development Project",
      examples: [
        "AI Study Buddy: An Interactive Learning Assistant",
        "AI-Powered Professional Networking Assistant",
        "AI-Powered Marketing Platform",
        "AI-Powered Financial Analyst",
        "AI Legal Advisor",
        "AI Meditation Coach",
        "AI Thought Management App",
        "AI Knowledge Management App",
      ],
      tools: ["Project Helper"],
    },
    {
      id: 21,
      activity: "Create an Art Work in Various Art Forms",
      examples: [
        "Mandala Art",
        "Painting",
        "3D Art",
        "Drawing",
        "Photography",
        "Digital Art",
        "Vector Art",
      ],
      tools: ["Image Generator"],
    },
    {
      id: 22,
      activity: "Co-create a Story with Agent Buddy",
      examples: [
        "The Seed Keepers",
        "Monsoon Mysteries",
        "The Healing River",
        "Stars of Our Ancestors",
        "The Plastic Hunters",
        "Grandmother's Garden",
        "The Festival of Light",
        "Vanishing Pollinators",
        "The Secret Life of Banyan Trees",
        "The Forgotten Well",
      ],
      tools: ["AI Tutor"],
    },
  ];